[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
  "-C",
  "link-arg=--nmagic",
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-Tmemory.x",
  "-C",
  "link-arg=-Map=output.map",
  # Code-size optimizations.
  # This requires nightly atm.
  # "-Z",
  # "trap-unreachable=no",
  # "-C",
  # "llvm-args=--inline-threshold=5",
  "-C",
  "no-vectorize-loops",
  "-C",
  "force-frame-pointers=no",
]
# Currently this requires a version of target-gen that has fixes for verification using the flash algo API.
# The version of target-gen in the probe-rs repo as of 2026/05/18 does not use the API for readback
# and also has issues with missing RTT output.
runner = "../../../probe-rs/target/debug/target-gen test template.yaml target/definition.yaml"
#runner = "target-gen test template.yaml target/definition.yaml"

[build]
target = "thumbv7em-none-eabihf"
